development:
  adapter: sqlite3
  database: db/db_development
  timeout: 30000

test: &test
  adapter: sqlite3
  database: db/db_test
  timeout: 30000

production:
  adapter: postgresql
  database: db_production
  timeout: 5000

cucumber:
  <<: *test